Repository noteu/noteu, pull requests merged in 2023-11, with the labels that each got.

#5 service 인터페이스 구현 추가
  README.md
  src/main/java/com/noteu/noteu/subject/service/impl/SubjectMemberServiceImpl.java
  src/main/java/com/noteu/noteu/subject/service/impl/SubjectServiceImpl.java
Labels: 🐛 bug

#14 회원가입 구현
  .github/ISSUE_TEMPLATE/pull_request_template.md
  src/main/java/com/noteu/noteu/config/SecurityConfig.java
  src/main/java/com/noteu/noteu/member/controller/MemberController.java
  src/main/java/com/noteu/noteu/member/converter/MemberConverter.java
  src/main/java/com/noteu/noteu/member/converter/impl/MemberConverterImpl.java
  src/main/java/com/noteu/noteu/member/dto/MemberDto.java
  src/main/java/com/noteu/noteu/member/dto/SignUpDto.java
  src/main/java/com/noteu/noteu/member/entity/Member.java
  src/main/java/com/noteu/noteu/member/entity/Role.java
  src/main/java/com/noteu/noteu/member/repository/MemberRepository.java
  src/main/java/com/noteu/noteu/member/service/MemberService.java
  src/main/resources/templates/fragments/member/signup.html
Labels: 💫 feat

#16 Member 데이터 추가
  src/main/resources/data.sql
Labels: 📝 docs, 💫 feat

#19 #8 feat : API 요청으로 채팅방 만들기
  build.gradle
  src/main/java/com/noteu/noteu/audit/AuditingFields.java
  src/main/java/com/noteu/noteu/chat/controller/ChatController.java
  src/main/java/com/noteu/noteu/chat/controller/ChatParticipantController.java
  src/main/java/com/noteu/noteu/chat/controller/ChatRoomController.java
  src/main/java/com/noteu/noteu/chat/converter/ChatConverter.java
  src/main/java/com/noteu/noteu/chat/converter/impl/ChatConverterImpl.java
  src/main/java/com/noteu/noteu/chat/dto/ChatMessageResponse.java
  src/main/java/com/noteu/noteu/chat/dto/request/ChatMessageRequestDto.java
  src/main/java/com/noteu/noteu/chat/dto/response/ChatMessageResponseDto.java
  src/main/java/com/noteu/noteu/chat/dto/response/ChatRoomResponseDto.java
  src/main/java/com/noteu/noteu/chat/entity/Chat.java
  src/main/java/com/noteu/noteu/chat/entity/ChatMessage.java
  src/main/java/com/noteu/noteu/chat/entity/ChatParticipant.java
  src/main/java/com/noteu/noteu/chat/entity/ChatRoom.java
  src/main/java/com/noteu/noteu/chat/entity/MessageType.java
  src/main/java/com/noteu/noteu/chat/repository/ChatMessageRepository.java
  src/main/java/com/noteu/noteu/chat/repository/ChatRepository.java
  src/main/java/com/noteu/noteu/chat/service/ChatParticipantService.java
  src/main/java/com/noteu/noteu/chat/service/ChatRoomService.java
  src/main/java/com/noteu/noteu/chat/service/ChatService.java
  src/main/java/com/noteu/noteu/chat/service/RestChatService.java
  src/main/java/com/noteu/noteu/chat/service/SocketChatService.java
  src/main/java/com/noteu/noteu/chat/service/impl/ChatParticipantServiceImpl.java
  src/main/java/com/noteu/noteu/chat/service/impl/ChatRoomServiceImpl.java
  src/main/java/com/noteu/noteu/chat/service/impl/ChatServiceImpl.java
  src/main/java/com/noteu/noteu/chat/service/impl/RestChatServiceImpl.java
  src/main/java/com/noteu/noteu/chat/service/impl/SocketChatServiceImpl.java
  src/main/java/com/noteu/noteu/config/ChatConfig.java
  src/main/java/com/noteu/noteu/config/SecurityConfig.java
  src/main/resources/templates/chat/room.html
  src/main/resources/templates/chat/roomdetail.html
Labels: 💫 feat

#26 #17 update : Layout 수정
  src/main/resources/templates/fragments/common/header.html
  src/main/resources/templates/fragments/common/script.html
  src/main/resources/templates/layout/test.html
Labels: ♻️ refactor, 🌈 frontend

#25 Jwt 로그인
  MemberHttpRequest.http
  build.gradle
  src/main/java/com/noteu/noteu/config/SecurityConfig.java
  src/main/java/com/noteu/noteu/member/controller/MemberController.java
  src/main/java/com/noteu/noteu/member/dto/MemberDetails.java
  src/main/java/com/noteu/noteu/member/dto/MemberInfo.java
  src/main/java/com/noteu/noteu/member/dto/SignInDto.java
  src/main/java/com/noteu/noteu/member/dto/SignUpDto.java
  src/main/java/com/noteu/noteu/member/entity/Member.java
  src/main/java/com/noteu/noteu/member/exception/UserAlreadyExistAuthenticationException.java
  src/main/java/com/noteu/noteu/member/repository/MemberRepository.java
  src/main/java/com/noteu/noteu/member/security/config/CustomFilterConfig.java
  src/main/java/com/noteu/noteu/member/security/filter/JwtAuthenticationFilter.java
  src/main/java/com/noteu/noteu/member/security/filter/JwtVerificationFilter.java
  src/main/java/com/noteu/noteu/member/security/handler/MemberAccessDeniedHandler.java
  src/main/java/com/noteu/noteu/member/security/handler/MemberAuthenticationEntryPoint.java
  src/main/java/com/noteu/noteu/member/security/handler/MemberAuthenticationFailureHandler.java
  src/main/java/com/noteu/noteu/member/security/handler/MemberAuthenticationSuccessHandler.java
  src/main/java/com/noteu/noteu/member/security/utils/ErrorResponder.java
  src/main/java/com/noteu/noteu/member/security/utils/JwtUtils.java
  src/main/java/com/noteu/noteu/member/service/MemberDetailsService.java
  src/main/java/com/noteu/noteu/member/service/MemberService.java
  src/main/java/com/noteu/noteu/member/service/UserDetailsManager.java
  src/main/resources/templates/fragments/member/sign_in.html
  src/main/resources/templates/fragments/member/sign_up.html
  src/main/resources/templates/fragments/member/signup.html
  src/test/java/com/noteu/noteu/member/controller/MemberControllerTest.java
Labels: 💫 feat

#29 #28 feat: 로그인 시 쿠키 생성, 토큰 값 담기
  src/main/java/com/noteu/noteu/member/controller/MemberController.java
  src/main/java/com/noteu/noteu/member/dto/MemberInfo.java
  src/main/java/com/noteu/noteu/member/security/filter/JwtAuthenticationFilter.java
  src/main/java/com/noteu/noteu/member/security/filter/JwtVerificationFilter.java
  src/main/java/com/noteu/noteu/member/security/handler/MemberAuthenticationEntryPoint.java
  src/main/java/com/noteu/noteu/member/security/handler/MemberAuthenticationSuccessHandler.java
  src/main/resources/templates/fragments/member/sign_in.html
Labels: 💫 feat

#31 #30 fix: 쿠키 설정 추가
  src/main/java/com/noteu/noteu/member/security/filter/JwtAuthenticationFilter.java
Labels: 🐛 bug

#32 #30 fix: 로그인 후 과목 목록으로 이동
  src/main/resources/templates/fragments/member/sign_in.html
Labels: 🐛 bug

#34 #33 fix: 로그인 후 principal 객체 null 오류 수정
  src/main/resources/templates/fragments/member/sign_in.html
Labels: 🐛 bug

#36 인증 방식 토큰에서 세션으로 변경
  build.gradle
  src/main/java/com/noteu/noteu/config/SecurityConfig.java
  src/main/java/com/noteu/noteu/member/controller/AuthController.java
  src/main/java/com/noteu/noteu/member/converter/MemberConverter.java
  src/main/java/com/noteu/noteu/member/dto/MemberDetails.java
  src/main/java/com/noteu/noteu/member/dto/MemberInfo.java
  src/main/java/com/noteu/noteu/member/security/config/CustomFilterConfig.java
  src/main/java/com/noteu/noteu/member/security/filter/JwtAuthenticationFilter.java
  src/main/java/com/noteu/noteu/member/security/filter/JwtVerificationFilter.java
  src/main/java/com/noteu/noteu/member/security/handler/CustomAuthenticationSuccessHandler.java
  src/main/java/com/noteu/noteu/member/security/handler/MemberAccessDeniedHandler.java
  src/main/java/com/noteu/noteu/member/security/handler/MemberAuthenticationEntryPoint.java
  src/main/java/com/noteu/noteu/member/security/handler/MemberAuthenticationFailureHandler.java
  src/main/java/com/noteu/noteu/member/security/handler/MemberAuthenticationSuccessHandler.java
  src/main/java/com/noteu/noteu/member/security/utils/AppConfig.java
  src/main/java/com/noteu/noteu/member/security/utils/JwtUtils.java
  src/main/java/com/noteu/noteu/member/service/MemberDetailsService.java
  src/main/resources/templates/fragments/member/login.html
  src/main/resources/templates/fragments/member/sign_in.html
  src/test/java/com/noteu/noteu/member/controller/AuthControllerTest.java
Labels: 💫 feat

#39 소셜 로그인
  .gitignore
  src/main/java/com/noteu/noteu/config/AppConfig.java
  src/main/java/com/noteu/noteu/config/SecurityConfig.java
  src/main/java/com/noteu/noteu/member/dto/SignInDto.java
  src/main/java/com/noteu/noteu/member/handler/CustomAuthenticationSuccessHandler.java
  src/main/java/com/noteu/noteu/member/oauth2/GoogleMemberInfo.java
  src/main/java/com/noteu/noteu/member/oauth2/KakaoMemberInfo.java
  src/main/java/com/noteu/noteu/member/oauth2/NaverMemberInfo.java
  src/main/java/com/noteu/noteu/member/oauth2/OAuth2MemberInfo.java
  src/main/java/com/noteu/noteu/member/security/utils/ErrorResponder.java
  src/main/java/com/noteu/noteu/member/service/OauthDetailsService.java
  src/main/resources/templates/fragments/member/login.html
  src/test/java/com/noteu/noteu/member/controller/AuthControllerTest.java
Labels: 💫 feat

#40 #8 feat : 채팅방 입장
  ChatHttpRequest.http
  MemberHttpRequest.http
  build.gradle
  src/main/java/com/noteu/noteu/chat/controller/ChatRoomController.java
  src/main/java/com/noteu/noteu/chat/converter/ChatConverter.java
  src/main/java/com/noteu/noteu/chat/dto/response/ChatParticipantResponseDto.java
  src/main/java/com/noteu/noteu/chat/dto/response/ChatRoomResponseDto.java
  src/main/java/com/noteu/noteu/chat/entity/ChatParticipant.java
  src/main/java/com/noteu/noteu/chat/entity/ChatRoom.java
  src/main/java/com/noteu/noteu/chat/repository/ChatRoomRepository.java
  src/main/java/com/noteu/noteu/chat/repository/querydsl/ChatRoomRepositoryCustom.java
  src/main/java/com/noteu/noteu/chat/repository/querydsl/impl/ChatRoomRepositoryCustomImpl.java
  src/main/java/com/noteu/noteu/chat/service/RestChatService.java
  src/main/java/com/noteu/noteu/chat/service/impl/RestChatServiceImpl.java
  src/main/java/com/noteu/noteu/chat/service/impl/SocketChatServiceImpl.java
  src/main/java/com/noteu/noteu/member/dto/response/MemberResponseDto.java
  src/main/resources/data.sql
  src/main/resources/static/assets/css/app-modern-rtl.min.css
  src/main/resources/static/assets/js/app.min.js
  src/main/resources/static/assets/js/pages/demo.apex-heatmap.js
  src/main/resources/static/assets/vendor/simplebar/simplebar.min.js
  src/main/resources/static/js/chat/chat.js
  src/main/resources/templates/fragments/common/sidebar1.html
  src/main/resources/templates/fragments/content/chat/apps-chat.html
  src/main/resources/templates/fragments/content/chat/room.html
  src/main/resources/templates/layout/chat/chat.html
Labels: 💫 feat

#42 로그아웃 및 view 작업
  src/main/java/com/noteu/noteu/config/SecurityConfig.java
  src/main/java/com/noteu/noteu/member/dto/MemberDetails.java
  src/main/java/com/noteu/noteu/member/dto/MemberInfo.java
  src/main/java/com/noteu/noteu/member/handler/CustomAuthenticationSuccessHandler.java
  src/main/java/com/noteu/noteu/member/service/MemberDetailsService.java
  src/main/java/com/noteu/noteu/member/service/OauthDetailsService.java
  src/main/resources/static/file/profile/default.png
  src/main/resources/templates/fragments/common/sidebar1.html
  src/main/resources/templates/fragments/common/sidebar2.html
  src/main/resources/templates/fragments/common/topbar.html
  src/main/resources/templates/fragments/member/login.html
Labels: 💫 feat, 🌈 frontend

#48 자료실 CRUD 구현
  src/main/java/com/noteu/noteu/reference/controller/ReferenceController.java
  src/main/java/com/noteu/noteu/reference/controller/ReferenceRoomController.java
  src/main/java/com/noteu/noteu/reference/converter/Impl/ReferenceRoomConverterImpl.java
  src/main/java/com/noteu/noteu/reference/converter/ReferenceRoomConverter.java
  src/main/java/com/noteu/noteu/reference/dto/ReferenceDTO.java
  src/main/java/com/noteu/noteu/reference/dto/ReferenceRoomDTO.java
  src/main/java/com/noteu/noteu/reference/dto/request/AddRequestReferenceRoomDTO.java
  src/main/java/com/noteu/noteu/reference/dto/request/EditRequestReferenceRoomDTO.java
  src/main/java/com/noteu/noteu/reference/dto/response/DetailResponseReferenceRoomDTO.java
  src/main/java/com/noteu/noteu/reference/dto/response/GetAllResponseReferenceRoomDTO.java
  src/main/java/com/noteu/noteu/reference/entity/Reference.java
  src/main/java/com/noteu/noteu/reference/entity/ReferenceRoom.java
  src/main/java/com/noteu/noteu/reference/repository/ReferenceRepository.java
  src/main/java/com/noteu/noteu/reference/repository/ReferenceRoomRepository.java
  src/main/java/com/noteu/noteu/reference/service/ReferenceRoomService.java
  src/main/java/com/noteu/noteu/reference/service/ReferenceService.java
  src/main/java/com/noteu/noteu/reference/service/impl/ReferenceRoomServiceImpl.java
  src/main/java/com/noteu/noteu/reference/service/impl/ReferenceServiceImpl.java
  src/main/resources/static/css/reference/file-thumbnail.css
  src/main/resources/static/js/reference/add-submit.js
  src/main/resources/static/js/reference/edit-submit.js
  src/main/resources/static/js/reference/list.js
  src/main/resources/templates/fragments/content/reference/add-form.html
  src/main/resources/templates/fragments/content/reference/detail.html
  src/main/resources/templates/fragments/content/reference/edit-form.html
  src/main/resources/templates/fragments/content/reference/list.html
  src/main/resources/templates/layout/reference/add.html
  src/main/resources/templates/layout/reference/detail.html
  src/main/resources/templates/layout/reference/edit.html
  src/main/resources/templates/layout/reference/list.html
Labels: 💫 feat, 🌈 frontend

#52 채팅 소켓 연결구현
  src/main/java/com/noteu/noteu/chat/controller/ChatController.java
  src/main/java/com/noteu/noteu/chat/controller/ChatRoomController.java
  src/main/java/com/noteu/noteu/chat/converter/ChatConverter.java
  src/main/java/com/noteu/noteu/chat/dto/response/ChatRoomInfoResponseDto.java
  src/main/java/com/noteu/noteu/chat/dto/response/ChatRoomResponseDto.java
  src/main/java/com/noteu/noteu/chat/repository/ChatMessageRepository.java
  src/main/java/com/noteu/noteu/chat/repository/querydsl/ChatRoomRepositoryCustom.java
  src/main/java/com/noteu/noteu/chat/repository/querydsl/impl/ChatRoomRepositoryCustomImpl.java
  src/main/java/com/noteu/noteu/chat/service/RestChatService.java
  src/main/java/com/noteu/noteu/chat/service/impl/RestChatServiceImpl.java
  src/main/resources/static/js/chat/chat.js
  src/main/resources/templates/fragments/content/chat/apps-chat.html
  src/main/resources/templates/fragments/content/chat/room.html
  src/main/resources/templates/fragments/content/chat/roomdetail.html
Labels: 🔥 backend, 💫 feat, 🌈 frontend

#57 #49 refactor: 사이드바 수정
  src/main/java/com/noteu/noteu/reference/controller/ReferenceRoomController.java
  src/main/resources/templates/fragments/common/sidebar2.html
Labels: ♻️ refactor, 🌈 frontend

#63 #62 feat : 채팅방 생성
  src/main/java/com/noteu/noteu/chat/controller/ChatRoomController.java
  src/main/java/com/noteu/noteu/chat/converter/ChatConverter.java
  src/main/java/com/noteu/noteu/chat/dto/ChatRoomResponse.java
  src/main/java/com/noteu/noteu/chat/dto/response/ChatRoomExistResponseDto.java
  src/main/java/com/noteu/noteu/chat/dto/response/ChatRoomResponseDto.java
  src/main/java/com/noteu/noteu/chat/repository/ChatParticipantRepository.java
  src/main/java/com/noteu/noteu/chat/repository/querydsl/ChatRoomRepositoryCustom.java
  src/main/java/com/noteu/noteu/chat/repository/querydsl/impl/ChatRoomRepositoryCustomImpl.java
  src/main/java/com/noteu/noteu/chat/service/RestChatService.java
  src/main/java/com/noteu/noteu/chat/service/impl/RestChatServiceImpl.java
  src/main/java/com/noteu/noteu/subject/repository/SubjectMemberRepository.java
  src/main/resources/data.sql
  src/main/resources/static/js/chat/chat.js
  src/main/resources/templates/fragments/content/chat/apps-chat.html
Labels: 🔥 backend, 💫 feat

#64 #54 feat: 비밀번호 변경
  src/main/java/com/noteu/noteu/member/controller/MemberController.java
  src/main/java/com/noteu/noteu/member/dto/MemberPasswordDto.java
  src/main/java/com/noteu/noteu/member/entity/Member.java
  src/main/java/com/noteu/noteu/member/service/MemberDetailsService.java
  src/main/java/com/noteu/noteu/member/service/UserDetailsManager.java
  src/main/resources/templates/fragments/content/member/change_password.html
  src/main/resources/templates/layout/member/change_password.html
Labels: 💫 feat

#80 자료실 제목으로 검색 기능 추가
  src/main/java/com/noteu/noteu/reference/controller/ReferenceRoomController.java
  src/main/java/com/noteu/noteu/reference/repository/ReferenceRoomRepository.java
  src/main/java/com/noteu/noteu/reference/service/ReferenceRoomService.java
  src/main/java/com/noteu/noteu/reference/service/impl/ReferenceRoomServiceImpl.java
  src/main/resources/static/js/reference/list.js
  src/main/resources/templates/fragments/content/reference/detail.html
  src/main/resources/templates/fragments/content/reference/edit-form.html
  src/main/resources/templates/fragments/content/reference/list.html
  src/main/resources/templates/layout/reference/list.html
Labels: 🔥 backend, 💫 feat, 🌈 frontend

#82 실시간 응답 대기 구현
  .gitignore
  build.gradle
  src/main/java/com/noteu/noteu/chat/controller/ChatRoomController.java
  src/main/java/com/noteu/noteu/chat/converter/ChatConverter.java
  src/main/java/com/noteu/noteu/member/dto/response/MemberResponseDto.java
  src/main/java/com/noteu/noteu/sse/SseController.java
  src/main/java/com/noteu/noteu/sse/SseEmitterService.java
  src/main/java/com/noteu/noteu/sse/dto/SseNewChatDto.java
  src/main/resources/static/js/chat/chat.js
  src/main/resources/static/js/sse/sse.js
  src/main/resources/templates/layout/chat/chat.html
Labels: 🔥 backend, 💫 feat, 🌈 frontend

#87 질문게시판 검색 기능 추가 및 페이지네이션 / 버그 수정 / 댓글 출력 부분 수정 / 프로필 추가
  src/main/java/com/noteu/noteu/member/repository/MemberRepository.java
  src/main/java/com/noteu/noteu/question/controller/QuestionPostController.java
  src/main/java/com/noteu/noteu/question/converter/QuestionPostConverter.java
  src/main/java/com/noteu/noteu/question/dto/request/SearchRequestQuestionPostDTO.java
  src/main/java/com/noteu/noteu/question/dto/response/DetailResponseQuestionPostDTO.java
  src/main/java/com/noteu/noteu/question/dto/response/GetAllResponseQuestionPostDTO.java
  src/main/java/com/noteu/noteu/question/dto/response/ResponseQuestionCommentDTO.java
  src/main/java/com/noteu/noteu/question/repository/QuestionCommentRepository.java
  src/main/java/com/noteu/noteu/question/repository/QuestionPostRepository.java
  src/main/java/com/noteu/noteu/question/service/QuestionPostService.java
  src/main/java/com/noteu/noteu/question/service/impl/QuestionPostServiceImpl.java
  src/main/resources/static/js/question/add-submit.js
  src/main/resources/static/js/question/detail.js
  src/main/resources/static/js/question/edit-submit.js
  src/main/resources/static/js/question/list.js
  src/main/resources/templates/fragments/content/question/add-form.html
  src/main/resources/templates/fragments/content/question/detail.html
  src/main/resources/templates/fragments/content/question/edit-form.html
  src/main/resources/templates/fragments/content/question/list.html
  src/main/resources/templates/layout/question/add.html
  src/main/resources/templates/layout/question/detail.html
  src/main/resources/templates/layout/question/edit.html
Labels: 🐛 bug, ♻️ refactor, 🔥 backend, 💫 feat, 🌈 frontend

#90 자료실 수정 및 삭제 시 재확인 로직 추가
  src/main/resources/static/js/reference/add-submit.js
  src/main/resources/static/js/reference/detail.js
  src/main/resources/static/js/reference/edit-submit.js
  src/main/resources/static/js/reference/list.js
  src/main/resources/templates/fragments/content/reference/add-form.html
  src/main/resources/templates/fragments/content/reference/detail.html
  src/main/resources/templates/fragments/content/reference/edit-form.html
  src/main/resources/templates/fragments/content/reference/list.html
  src/main/resources/templates/layout/reference/add.html
  src/main/resources/templates/layout/reference/detail.html
  src/main/resources/templates/layout/reference/edit.html
Labels: ♻️ refactor, 🌈 frontend

#92 댓글 id / 댓글 삭제 버튼 수정
  src/main/resources/static/js/question/detail.js
Labels: 🐛 bug, 🌈 frontend

#94 #93 bug : 채팅방을 못 불러오는 버그 수정
  src/main/java/com/noteu/noteu/chat/repository/querydsl/impl/ChatRoomRepositoryCustomImpl.java
  src/main/java/com/noteu/noteu/chat/service/impl/RestChatServiceImpl.java
  src/main/resources/static/js/chat/chat.js
Labels: 🐛 bug

#98 #97 bug: input_subject_code.js
  src/main/resources/static/js/subject/input_subject_code.js
Labels: 🐛 bug

#100 채팅 이미지 추가
  src/main/java/com/noteu/noteu/chat/controller/ChatRoomController.java
  src/main/resources/static/js/chat/chat.js
  src/main/resources/templates/fragments/content/chat/apps-chat.html
Labels: 🔥 backend

#105 자료실 파일 경로 수정
  src/main/java/com/noteu/noteu/contoller/TemplateController.java
  src/main/java/com/noteu/noteu/reference/controller/ReferenceRoomController.java
  src/main/resources/static/assets/images/noteuLogo.png
  src/main/resources/templates/fragments/content/reference/detail.html
  src/main/resources/templates/fragments/content/reference/list.html
  src/main/resources/templates/layout/test.html
Labels: 🐛 bug, 🔥 backend

#107 채팅수 삭제, 바디헤더 변경
  src/main/resources/static/js/chat/chat.js
  src/main/resources/templates/fragments/content/chat/apps-chat.html
Labels: ♻️ refactor, 🌈 frontend

#111 홈 페이지 추가
  src/main/resources/static/js/index/index.js
  src/main/resources/templates/index.html
Labels: 💫 feat, 🌈 frontend

#113 에러 페이지 로고 변경
  src/main/resources/templates/layout/error/pages-404.html
  src/main/resources/templates/layout/error/pages-500.html
  src/main/resources/templates/layout/error/pages-maintenance.html
Labels: ♻️ refactor, 🌈 frontend

#116 질문게시글 프로필 사진 크기 및 작성자 명 위치 수정
  src/main/resources/templates/fragments/content/question/detail.html
Labels: ♻️ refactor, 🌈 frontend

#117 홈 페이지 위치 속성 추가
  src/main/resources/templates/index.html
Labels: ♻️ refactor, 🌈 frontend

#119 로고 디자인 변경, 프론트 수정
  src/main/java/com/noteu/noteu/member/controller/MemberController.java
  src/main/java/com/noteu/noteu/member/service/OauthDetailsService.java
  src/main/resources/static/assets/images/noteuLogo.png
  src/main/resources/static/js/member/account.js
  src/main/resources/static/js/member/sign_up.js
  src/main/resources/templates/fragments/common/sidebar1.html
  src/main/resources/templates/fragments/common/sidebar2.html
  src/main/resources/templates/fragments/common/topbar.html
  src/main/resources/templates/fragments/content/member/account.html
  src/main/resources/templates/fragments/content/member/change_password.html
  src/main/resources/templates/fragments/content/member/change_profile.html
  src/main/resources/templates/fragments/content/member/login.html
  src/main/resources/templates/fragments/content/member/logout.html
  src/main/resources/templates/fragments/content/member/sign_up.html
Labels: 🐛 bug, 🌈 frontend

#121 #120 refactor : 채팅 선택표시 수정
  src/main/resources/static/js/chat/chat.js
Labels: 🌈 frontend

#123 홈페이지 프론트 디자인
  src/main/resources/static/assets/images/book.png
  src/main/resources/static/assets/images/logoBook.png
  src/main/resources/static/assets/images/noteuLogoBlack.png
  src/main/resources/templates/index.html
Labels: 🌈 frontend

#127 페이지 링크 수정
  src/main/resources/templates/fragments/content/question/add-form.html
  src/main/resources/templates/fragments/content/question/edit-form.html
  src/main/resources/templates/fragments/content/question/list.html
  src/main/resources/templates/fragments/content/reference/add-form.html
  src/main/resources/templates/fragments/content/reference/detail.html
  src/main/resources/templates/fragments/content/reference/edit-form.html
  src/main/resources/templates/fragments/content/reference/list.html
Labels: ♻️ refactor, 🌈 frontend

#128 질문게시판 댓글 작성자 badge 표시
  src/main/java/com/noteu/noteu/question/converter/QuestionPostConverter.java
  src/main/java/com/noteu/noteu/question/dto/response/ResponseQuestionCommentDTO.java
  src/main/resources/static/js/question/detail.js
  src/main/resources/templates/fragments/content/question/detail.html
Labels: 🔥 backend, 💫 feat, 🌈 frontend

#129 favicon 등록
  src/main/resources/templates/fragments/common/header.html
Labels: 🌈 frontend

#130 과목, 과제 페이지 링크 수정
  src/main/resources/templates/fragments/content/notice/add_content.html
  src/main/resources/templates/fragments/content/notice/detail_content.html
  src/main/resources/templates/fragments/content/notice/edit_content.html
  src/main/resources/templates/fragments/content/notice/list_content.html
  src/main/resources/templates/fragments/content/subject/add_content.html
  src/main/resources/templates/fragments/content/subject/detail_content.html
  src/main/resources/templates/fragments/content/subject/input_subject_code_content.html
  src/main/resources/templates/fragments/content/subject/list_content.html
  src/main/resources/templates/fragments/content/task/add_content.html
  src/main/resources/templates/fragments/content/task/detail_content.html
  src/main/resources/templates/fragments/content/task/edit_content.html
  src/main/resources/templates/fragments/content/task/list_content.html
Labels: 🌈 frontend

#131 #122 feat : 버튼 카운트
  src/main/resources/static/js/index/index.js
  src/main/resources/templates/index.html
Labels: 💫 feat, 🌈 frontend

#133 과목 코드 복사 버그 해결
  src/main/resources/static/js/subject/list.js
Labels: 🐛 bug
